<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="robot">

    <!-- Define properties for base and wheels -->
    <xacro:property name="base_radius" value="18"/>
    <xacro:property name="base_length" value="1.4"/>
    <xacro:property name="wheel_radius" value="2.9"/>
    <xacro:property name="wheel_length" value="2.56"/>
    <xacro:property name="wheel_offset" value="12.73"/>
    <xacro:property name="wheel_height" value="2.0"/>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${base_length / 2}"/>
        </visual>
    </link>

    <!-- Macro for creating wheels -->
    <xacro:macro name="wheel" params="wheel_name wheel_origin_xyz wheel_origin_rpy">
        <link name="${wheel_name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </visual>
        </link>

        <joint name="${wheel_name}-base" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}"/>
            <origin xyz="${wheel_origin_xyz}" rpy="${wheel_origin_rpy}"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <!-- Create four wheels using the wheel macro -->
    <xacro:wheel wheel_name="wheel1" wheel_origin_xyz="${wheel_offset} ${wheel_offset} ${wheel_height}" wheel_origin_rpy="-0.85 1.57 0"/>
    <xacro:wheel wheel_name="wheel2" wheel_origin_xyz="-${wheel_offset} ${wheel_offset} ${wheel_height}" wheel_origin_rpy="-0.85 -1.57 0"/>
    <xacro:wheel wheel_name="wheel3" wheel_origin_xyz="-${wheel_offset} -${wheel_offset} ${wheel_height}" wheel_origin_rpy="0.85 -1.57 0"/>
    <xacro:wheel wheel_name="wheel4" wheel_origin_xyz="${wheel_offset} -${wheel_offset} ${wheel_height}" wheel_origin_rpy="0.85 1.57 0"/>

</robot>
